# Generated by Django 4.2.6 on 2024-05-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topicmember_topic_alter_topicmember_user'),
        ('messaging', '0002_alter_topicchatchannel_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicchatmessage',
            old_name='message_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='topicchatchannel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='room_member', to='topics.topicmember'),
        ),
    ]
