# Generated by Django 4.2.6 on 2024-02-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_topicroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicchatmessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.topicroom'),
        ),
        migrations.AlterField(
            model_name='topicchatmessage',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.topicchatchannel'),
        ),
    ]
