# Generated by Django 4.2.6 on 2024-03-07 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_topicchatmessage_room_alter_topicchatmessage_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicchatmessage',
            name='room',
        ),
        migrations.AddField(
            model_name='topicchatchannel',
            name='code',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topicchatchannel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_room_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicchatchannel',
            name='members',
            field=models.ManyToManyField(related_name='topic_room_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicchatchannel',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Text Channel'), (2, 'Room')], default=1),
        ),
        migrations.DeleteModel(
            name='TopicRoom',
        ),
    ]
