# Generated by Django 4.2.6 on 2024-03-08 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0004_remove_topicchatmessage_room_topicchatchannel_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicchatchannel',
            old_name='code',
            new_name='invite_code',
        ),
        migrations.AlterField(
            model_name='topicchatchannel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='topic_room_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
