# Generated by Django 4.2.6 on 2024-05-23 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmember',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_members', to='topics.topic'),
        ),
        migrations.AlterField(
            model_name='topicmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
