# Generated by Django 4.2.6 on 2024-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='system_message_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
