# Generated by Django 4.2.6 on 2024-01-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_notification_system_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='system_message_content',
            new_name='notification_content',
        ),
    ]
