# Generated by Django 4.1.1 on 2023-08-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replying_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.reply'),
        ),
    ]
